USE it_course_management;

CREATE TABLE LECTURE (
    LECTUREID INT PRIMARY KEY AUTO_INCREMENT,
    LECTURENAME NVARCHAR(512) NOT NULL,
    COURSEID INT NOT NULL,
    VIDEOURL VARCHAR(1024) NOT NULL,
    DURATION SMALLINT NOT NULL CHECK(DURATION > 0),
    LECTUREDESCRIPTION NVARCHAR(512),
    FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID) ON DELETE CASCADE
);

CREATE TABLE LECTUREPROGRESS (
    USERID INT NOT NULL,
    LECTUREID INT NOT NULL,
    STATUS ENUM('in-progress', 'done', 'unfinished') NOT NULL DEFAULT 'unfinished',
    PRIMARY KEY (USERID, LECTUREID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
    FOREIGN KEY (LECTUREID) REFERENCES LECTURE(LECTUREID) ON DELETE CASCADE
);

CREATE TABLE CATEGORIES (
    CATEGORYID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORYNAME NVARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE COURSECATEGORIES (
    COURSEID INT NOT NULL,
    CATEGORYID INT NOT NULL,
    PRIMARY KEY (COURSEID, CATEGORYID),
    FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES(CATEGORYID) ON DELETE CASCADE
);

CREATE TABLE MYLEARNING (
    USERID INT NOT NULL,
    COURSEID INT NOT NULL,
    COURSESTATUS ENUM('in-progress', 'finished') NOT NULL DEFAULT 'in-progress',
    LASTACCESSEDAT DATETIME,
    PRIMARY KEY (USERID, COURSEID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
    FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID) ON DELETE CASCADE
);

CREATE TABLE CERTIFICATE (
    CERTIFICATEID INT PRIMARY KEY AUTO_INCREMENT,
    CERTIFICATENAME NVARCHAR(512) NOT NULL,
    COURSEID INT NOT NULL,
    FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID) ON DELETE CASCADE
);

CREATE TABLE USERCERTIFICATE (
    CERTIFICATEID INT NOT NULL,
    USERID INT NOT NULL,
    ISSUEDATE DATE NOT NULL,
    PRIMARY KEY (CERTIFICATEID, USERID),
    FOREIGN KEY (CERTIFICATEID) REFERENCES CERTIFICATE(CERTIFICATEID) ON DELETE CASCADE,
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);

CREATE TABLE MYWISHLIST (
    USERID INT NOT NULL,
    COURSEID INT NOT NULL,
    ADDEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USERID, COURSEID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
    FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID) ON DELETE CASCADE
);



